server:
  port: 8080
  servlet:
    context-path: /eap-order

spring:
  application:
    name: eap-order
  datasource:
    url: jdbc:postgresql://localhost:5432/eapdb
    username: admin
    password: admin123

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: dev
    drop-first: false

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      message-converter: jackson2JsonMessageConverter
      mandatory: true
    listener:
      simple:
        prefetch: 10
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000
  data:
    redis:
      host: localhost
      port: 6379
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: eap-order

logging:
  level:
    '[com.eap.eap_order]': DEBUG
    '[org.springframework.web]': DEBUG

eap:
  order-publisher:
    confirm-timeout-ms: 5000
  backpressure:
    wallet-queue:
      enabled: true
      hard-threshold: 10000
      cache-ttl-ms: 1000
      hard-retry-after-seconds: 5
  wallet:
    base-url: http://localhost:8081/eap-wallet
  matchEngine:
    base-url: http://localhost:8082/match-engine
  order:
    listeners:
      asset-reservation-confirmed:
        concurrency: 8
      asset-reservation-failed:
        concurrency: 4
      order-matched:
        concurrency: 4
      trade-executed:
        concurrency: 4
